export default {
    white: "#fff",
  };
  

export const image = {
  Headers:{
    '0':'Our Offerings', 
    '1':'Not Feeling Well ?', 
    '2':'Explore Deals Offers For You  Upto 100% Off    ......',
    '3':'Search by health care concerns..', 
    '4':'Search by Speciality ...', 
    '5':'Skin Related', 
    '6':'General Physician', 
    '7':'Common Health Issues', 
    '8':'CHOOSE FROM TOP SPECIALITIES', 
    '9':'Dermatology', 
    '10':'Ear-Nose-Throat(ENT) Specialist', 
    '11':'Orthopedic'
  },
  sliding:{
    '0': require('./images/1.jpg'),
    '1': require('./images/2.jpg'),
    '2': require('./images/3.jpg'),
    '3': require('./images/4.jpg'),
    '4': require('./images/1.jpg'),
  },
  department: {
    'Pimples & Ache '   : require('./images/icon/pimples.jpg'),
    'Muscle weakness'   : require('./images/icon/muscle.jpg'),
    'Feaver'            : require('./images/icon/feaver.jpg'),
    'Breathing Problems': require('./images/icon/lung.jpg'),
    'Cough in Child'    : require('./images/icon/childCough.jpg'),
  },
  category:{
    'Find Doctors Near You': require('./images/icon/ic_physician_blue.png'),
    'Instant Video Consultation': require('./images/icon/doctors.jpg'),
    'Medicines': require('./images/icon/pills.png'),
    'Lab Tests': require('./images/icon/ic_pathology.png'),
    'Surgeries': require('./images/icon/heart.jpg'),
  },
  offerscard:{
    'heart': require('./images/1.jpg'),
    'lung': require('./images/2.jpg'),
    'kidney': require('./images/3.jpg'),
    'brain': require('./images/4.jpg'),
    'cancer': require('./images/1.jpg'),
  },
  SeemoreMainDepartments:{
    'Pimples & Ache '   : require('./images/icon/pimples.jpg'),
    'Muscle Weakness'   : require('./images/icon/muscle.jpg'),
    'Feaver'         : require('./images/icon/feaver.jpg'),
    'Breathing Problems': require('./images/icon/lung.jpg'),
    'Cough in Child'    : require('./images/icon/childCough.jpg'),
    'Frequent Urination': require('./images/icon/urination.jpg'),
    'Diabities': require('./images/icon/diabaties.jpg'),
    'obesity': require('./images/icon/obesity.jpg'),
    'Toothache': require('./images/icon/tooth.jpg'),
    'Pregancy Issues': require('./images/icon/pgissue.jpg'),
    'Stomach Pain': require('./images/icon/stomachpain.jpg'),
    'Vertigo': require('./images/icon/vergito.jpg'),
    'Eczema': require('./images/icon/Eczema.jpg'),
    'Headaches': require('./images/icon/Headaches.jpg'),
    'Fungal infections': require('./images/icon/Fungal.jpg'),
    'Back Pain': require('./images/icon/Back.jpg'),
  },
  general:{
    'Feaver':   require('./images/icon/feaver.jpg'),
    'High BP': require('./images/icon/heart.jpg'),
    'Dizziness': require('./images/icon/vergito.jpg'),
    'Pneumonia': require('./images/icon/lung.jpg'),
  },
  Speciality:{
    'Coronavirus': require('./images/icon/Coronavirus.jpg'),
    'Gynaecology': require('./images/icon/pgissue.jpg'),
    'General Physician': require('./images/icon/Physician.jpg'),
    'Dermatology': require('./images/icon/pimples.jpg'),
    'Orthopedic': require('./images/icon/Orthopedic.jpg'),
    'Pediatrics': require('./images/icon/childCough.jpg'),
    'Sexology': require('./images/icon/Sexology.jpg'),
    'Psychiatry': require('./images/icon/stress.jpg'),
    'Stomach and Digesion': require('./images/icon/stomachpain.jpg'),
    'Ear, Nose, Throat': require('./images/icon/ent.jpg'),
    'Urology': require('./images/icon/urology.jpg'),
    'Neurology': require('./images/icon/Neurology.jpg'),
    'Cardiology': require('./images/icon/Cardiology.jpg'),
    'Diet and Nutrition': require('./images/icon/Physician.jpg'),
    'Diabetology':require('./images/icon/diabaties.jpg'),
    'Eye and Vision': require('./images/icon/eye.jpg'),
    'Dental':require('./images/icon/tooth.jpg'),
    'Pulmonology': require('./images/icon/lung.jpg'),
    'Ayurveda': require('./images/icon/Ayurveda.jpg'),
    'Homeopaty': require('./images/icon/Homeopaty.jpg'),
    'Cancer': require('./images/icon/Cancer.jpg'),
    'Physiotherapy': require('./images/icon/Physiotherapy.jpg'),
    'General Surgery':  require('./images/icon/Physician.jpg'),
    'Psychological Concelling':  require('./images/icon/stress.jpg'),
    'I have some other Problem':  require('./images/icon/Physician.jpg'),
    'Veternary': require('./images/icon/Veternary.jpg'),
    'Nephorology': require('./images/icon/urination.jpg'),
    'Endocrinology': require('./images/icon/Endocrinology.jpg'),
    'Rheummatology': require('./images/icon/Rheummatology.jpg')
  },
  Orthopedic:{
    'Knee pain': require('./images/icon/Orthopedic1.jpg'),
    'Shoulder Pain': require('./images/icon/Orthopedic2.jpg'),
    'Leg Pain': require('./images/icon/Orthopedic3.jpg'),
    'Carpal pain': require('./images/icon/Orthopedic4.jpg'),
  }, 
   ent:{
    'Sore Throat': require('./images/icon/SoreThroat.jpg'),
    'Snoring': require('./images/icon/Snoring.jpg'),
    'Coughing': require('./images/icon/cough.jpg'),
    'Mouth Sores': require('./images/icon/MouthSores.jpg'),
  },  
  Dermatology:{
    'Vitiligo': require('./images/icon/Vitiligo.jpg'),
    'Hair Loss': require('./images/icon/Hair.jpg'),
    'Acne Scars': require('./images/icon/Acne.jpg'),
    'Dandruff': require('./images/icon/Dandruff.jpg'),
  },

};